root = "."
tmp_dir = "/tmp/air"

[build]
  cmd = "go build -mod=vendor -o /tmp/air/main ./cmd/..."
  bin = "/tmp/air/main"
  delay = 1000
  exclude_dir = ["vendor", "tmp"]
  include_ext = ["go"]
  kill_delay = "0s"
  rerun = false
  send_interrupt = false
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
